services:
  - type: web
    name: gemini-notebook-mcp-tunnel
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    envVars:
      - key: CONTROL_PLANE_TUNNEL_ID
        value: tunnel_6ac90a67956c8191ac7650b9635e6be4
      - key: CONTROL_PLANE_API_KEY
        sync: false
      - key: NOTEBOOKLM_COOKIES
        sync: false
